### PR TITLE
Adds conventions to multiple optional binding and using Swift feature…

### PR DESCRIPTION
**Pull request by mrcoliva**
…s like map and filter.

### CODE REVIEW

**Comment by mrcoliva** [comment]
@mathiasnagler Actually I prefer writing this in one line (if the list of optional bindings isn't too long of course) since your solution results in undesired indentation issues, like this:

``` swift
if let 
    widget = widget, 
    url = options.url, 
    host = options.host {
    // code will be here indented exactly like the optional bindings
}
```

instead of this:

``` swift
if let widget = widget, url = options.url, host = options.host {
    // code will be here
}
```

These issues don't occur in your example, but we normally don't put opening braces on a new line.
If the list of optional bindings is longer like here: 

``` swift
if let 
    widget = widget, 
    url = options.url, 
    host = options.host,
    parameters = requestParameters,
    completionHandler = completionHandler {

    // code will be here (with leading new line maybe?)
}
```

then your solution is of course preferred.

Are there any other opinions about this?

**Comment by mrcoliva** [comment]
Good point about using trailing closures. However how should we handle spacing in consecutive function calls?

In the first example the trailing closure is visually more connected to `reduce` than to the `filter` it belongs to:

``` swift
let sum = moneyArray.filter { $0 > 30 }.reduce(0, combine: +)
```

In the second example we're solving the problem above but miss a whitespace before the closure.

``` swift
let sum = moneyArray.filter{ $0 > 30 }.reduce(0, combine: +)
```

**Comment by sebastianf** [comment]
I like this one more
`let sum = moneyArray.filter{ $0 > 30 }.reduce(0, combine: +)`

**Comment by sebastianf** [comment]
and if there are more than 2 assignments, with the closing braces not in a new line

```
if let 
    widget = widget, 
    url = options.url, 
    host = options.host,
    parameters = requestParameters,
    completionHandler = completionHandler {

    // code will be here (with leading new line maybe?)
}
```

**Comment by mathiasnagler** [comment]
@mrcoliva Can you fix the merge conflict so we can merge this?

**Pull request merged**
