### PR TITLE
API Design Guidelines (in progress)

### PR DESCRIPTION
**Pull request by mrcoliva**
This pull request adds a few suggestions for API design guidelines, in particular naming conventions.
The pull request is work in progress, e.g. rationals for some points have to be added. However feel free to comment additional suggestions and opinions on already addressed points.

### CODE REVIEW

**Comment by fonkadelic** [comment]
@mrcoliva Awesome! Is this adopted from the Apple Swift API guidelines?  I'm 👌 with all suggestions.

**Comment by mathiasnagler** [comment]
Great PR! I think this is an adoption of the Apple API guidelines. 

I wonder if we should split the `README.md` into a `CODESTYLE.md` and `APIGUIDELINES.md` or similar. I think the `README.md` starts to become to long.

What are your thoughts on that @mrcoliva, @fonkadelic?

**Comment by mrcoliva** [comment]
It's a mix of the most relevant parts of the guidelines on Swift.org, WWDC Session 403 and personal thoughts and examples.

I think splitting the `REAMDE.md` like @mathiasnagler suggested is a good idea, especially regarding PR #2 which will increase the size of `REAMDE.md` even more.

**Comment by sebastianf** [comment]
looks good.
about the extra md files, I think we can do this but it is not necessary

**Pull request merged**
